### ISSUE TITLE
[1.12.2] RPG-Gear Modeling issue if Galacticraft is installed.

### ISSUE THREAD

**Issue by SonicX8000** [ArtixAllMighty/Rpg-Inventory-2016#10]
*Minecraft*
1.12.2
-
*Forge*
14.23.2.2629
-
*Mods*
GalacticraftCore-1.12.2-4.0.1.158
Galacticraft-Planets-1.12.2-4.0.1.158
MicdoodleCore-1.12.2-4.0.1.158
rpginventory-1.12-5.3.0.0
subcommonlib-sublib-1.12.2-1.2.0.4
-

If you have any Necklaces, Gloves or Cloaks worn while having Galacticraft installed... the worn models won't follow the player's movement but instead will remain static-like as seen in the image down below.
![](https://cdn.discordapp.com/attachments/377171551155650560/425216316832612362/rpginventorymodelissue.PNG)
Oddly enough, the cloak still moves normally. Also a config to disable the item renders would be nice since there are a few mods that have 'gloves' and it causes some clipping issues like with Botania's Terrasteel Armor, Draconic Evolution Armors, etc. It's more noticeable with cloaks being worn with armors as the 'cloth' clips through the armor when moving.

This bug may also happen for older versions of Minecraft.

**Comment by radfast** [comment]
@Z-Tunic thanks for reporting this, and many thanks to @ArtixAllMighty for bringing it to our attention.

Please download [Galacticraft 4.0.1.162](https://micdoodle8.com/mods/galacticraft/downloads) (or later) for a fix for this.

**Comment by AbsolemJackdaw** [comment]
Problem solved, closing issue !
