### ISSUE TITLE
[1.12.2 - Bug] Mining Speed Buff Ring/Cloak doesn't work if Aether Legacy is installed.

### ISSUE THREAD

**Issue by SonicX8000** [ArtixAllMighty/Rpg-Inventory-2016#11]
Minecraft: 1.12.2
Forge: 14.23.2.2629

Mods:
rpginventory-1.12-5.3.0.0
subcommonlib-sublib-1.12.2-1.2.0.4
theoneprobe-1.12-1.4.21
topaddons-1.12.2-1.2.1
aether_legacy-1.12.2-v2.0

-----
I don't know where to report this exactly but... if Aether Legacy is installed it prevents the Mining Speed Buff Ring/Cloak from working properly. The speed doesn't increase with either equipment worn.

The One Probe + Addons mods were used in order to figure out the speeds as the mod shows info on certain things, such as a Progress Bar when Mining. In one game tick the Progress Bar showed this...

Pickaxe: Diamond
Block: Obsidian 
Ticks: 1
Note: *I basically just tap the Left Mouse Button a few times just to 'mine' in only one tick so the block resets.*

This is what it shows...
*0% without the Mining Buff.*
*2% with the Mining Buff.*

Now if Aether Legacy is installed... this is what it shows...
*0% without the Mining Buff.*
*0% with the Mining Buff.*

At first I was thinking the boost was small but going from 0% to 2% on a Obsidian Block while having the Mining Buff from wearing the ring is quite an increase. Not sure how much of a boost the cloak gives as I'll need to go find one again but... yea.

[Aether Legacy Issue #297](https://github.com/Modding-Legacy/Aether-Legacy/issues/297)

**Comment by AbsolemJackdaw** [comment]
nice to see it has been solved =)
