### ISSUE TITLE
Crash when placing an item in the wrong slot

### ISSUE THREAD

**Issue by WenXin20** [ArtixAllMighty/Rpg-Inventory-2016#2]
Forge 2094
Umbralux v2.0.0.1
Bma Addon v4.0.0.1
RPG Inventory v5.0.0.1
[Crash Report](http://pastebin.com/YNezzj3P)

**Comment by Lightone** [comment]
Same problem with Rpg-Inventory of Pet Buddy Mod

**Comment by AbsolemJackdaw** [comment]
any items other then jewelry shouldn't be able to go into the slots.
looking into it as we speak.
