### ISSUE TITLE
[1.10.2] Items destroyed with Gamerule KeepInventory: true

### ISSUE THREAD

**Issue by milano1110** [ArtixAllMighty/Rpg-Inventory-2016#3]
Basically what I said in the title. I play with gamerule KeepInventory: true and that lets me keep my inventory on death, but the RPG inventory gets erased. The items are not at the place I died so it does not drop them. I keep cheating them back, but that gets annoying after a while. I hope you can fix this issue.

Greetings Milano

**Comment by AbsolemJackdaw** [comment]
I need to double check if i have a 1.10.2 version laying around to fix this .... i doubt it though. will keep you updated

**Comment by Cynosphere** [comment]
Can confirm on 1.11.2 also.
