### ISSUE TITLE
Is it possible to add a config file?

### ISSUE THREAD

**Issue by 5igm** [ArtixAllMighty/Rpg-Inventory-2016#4]
Is it possible to add a config file and make the mod more configurable? I think if it is possible to change the value of items'damage, protection, etc by users, it will be better.

**Comment by AbsolemJackdaw** [comment]
sounds like an idea. feature will be for 1.12 though. i'm currently installing my new forge environement =)

**Comment by 5igm** [comment]
Thank you :)

**Comment by AbsolemJackdaw** [comment]
berserker mage archer mod now has a config for weapon/item/armor usage, damage, ...

**Comment by AbsolemJackdaw** [comment]
all adons now have config files ! this should settle this issue =)

**Comment by 5igm** [comment]
Hi! Do you still update 1.11.2?

**Comment by 5igm** [comment]
@ArtixAllMighty

**Comment by AbsolemJackdaw** [comment]
doubt it sorry. i dont have that code anymore
