### ISSUE TITLE
Crash on player death

### ISSUE THREAD

**Issue by Kregoras** [ArtixAllMighty/Rpg-Inventory-2016#8]
Whenever the player is killed during singleplayer the game crashes. Minecraft version 1.12.2

Crash report:

` Time: 10/2/17 1:39 PM Description: Ticking player java.lang.NullPointerException: Ticking player at subaraki.rpginventory.capability.playerinventory.RpgInventoryData.get(RpgInventoryData.java:31) at subaraki.rpginventory.handler.JeweleryEffectsHandler.getEmeraldNecklaceEffect(JeweleryEffectsHandler.java:75) at subaraki.rpginventory.handler.JeweleryEffectsHandler.onExpEvent(JeweleryEffectsHandler.java:62) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_JeweleryEffectsHandler_onExpEvent_LivingExperienceDropEvent.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:234) at net.minecraft.entity.EntityLivingBase.func_70609_aI(EntityLivingBase.java:384) at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:322) at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388) at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2083) at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232) at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) at java.lang.Thread.run(Unknown Source) A detailed walkthrough of the error, its code path and all known details is as follows: --------------------------------------------------------------------------------------- -- Head -- Thread: Server thread Stacktrace: at subaraki.rpginventory.capability.playerinventory.RpgInventoryData.get(RpgInventoryData.java:31) at subaraki.rpginventory.handler.JeweleryEffectsHandler.getEmeraldNecklaceEffect(JeweleryEffectsHandler.java:75) at subaraki.rpginventory.handler.JeweleryEffectsHandler.onExpEvent(JeweleryEffectsHandler.java:62) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_JeweleryEffectsHandler_onExpEvent_LivingExperienceDropEvent.invoke(.dynamic) at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) at net.minecraftforge.event.ForgeEventFactory.getExperienceDrop(ForgeEventFactory.java:234) at net.minecraft.entity.EntityLivingBase.func_70609_aI(EntityLivingBase.java:384) at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:322) at net.minecraft.entity.Entity.func_70071_h_(Entity.java:388) at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2083) at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:232) -- Player being ticked -- Details: Entity Type: null (net.minecraft.entity.player.EntityPlayerMP) Entity ID: 85 Entity Name: Ragnir Entity's Exact location: -1110.99, 4.00, -196.92 Entity's Block location: World: (-1111,4,-197), Chunk: (at 9,0,11 in -70,-13; contains blocks -1120,0,-208 to -1105,255,-193), Region: (-3,-1; contains chunks -96,-32 to -65,-1, blocks -1536,0,-512 to -1025,255,-1) Entity's Momentum: 0.00, -0.08, 0.00 Entity's Passengers: [] Entity's Vehicle: ~~ERROR~~ NullPointerException: null Stacktrace: 	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:382) at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:173) at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) -- Ticking connection -- Details: Connection: net.minecraft.network.NetworkManager@35100161 Stacktrace: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:179) at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185) at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) at java.lang.Thread.run(Unknown Source) -- System Details -- Details: Minecraft Version: 1.12.2 Operating System: Windows 10 (amd64) version 10.0 Java Version: 1.8.0_144, Oracle Corporation Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation Memory: 230836768 bytes (220 MB) / 501497856 bytes (478 MB) up to 2134114304 bytes (2035 MB) JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0 FML: MCP 9.42 Powered by Forge 14.23.0.2491 7 mods loaded, 7 mods active States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored | State | ID | Version | Source | Signature | |:--------- |:----------------- |:------------ |:------------------------------------ |:---------------------------------------- | | UCHIJAAAA | minecraft | 1.12.2 | minecraft.jar | None | | UCHIJAAAA | mcp | 9.42 | minecraft.jar | None | | UCHIJAAAA | FML | 8.0.99.99 | forge-1.12.2-14.23.0.2491.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | | UCHIJAAAA | forge | 14.23.0.2491 | forge-1.12.2-14.23.0.2491.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 | | UCHIJAAAA | mercurius_updater | 1.0 | MercuriusUpdater-1.12.2.jar | None | | UCHIJAAAA | subcommonlib | 1.2.0.1 | subcommonlib-sublib-1.12-1.2.0.1.jar | None | | UCHIJAAAA | rpginventory | 1.12 | rpginventory-1.12-5.2.0.0.jar | None | Loaded coremods (and transformers): GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread. Profiler Position: N/A (disabled) Player Count: 1 / 8; [EntityPlayerMP['Ragnir'/85, l='Prueba de muerte', x=-1110.99, y=4.00, z=-196.92]] Type: Integrated Server (map_client.txt) Is Modded: Definitely; Client brand changed to 'fml,forge'
 `

**Comment by AbsolemJackdaw** [comment]
this has been fixed in a previous commit but never build. expect an update within the hour to be up on curseforge
